<?php

namespace Movies\MovieBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

	public function getLastComments($limit)
	{
		return $this->_em
				    ->createQueryBuilder('c')
				    ->select('c')
				    ->from('MoviesMovieBundle:Comment', 'c')
				    ->orderBy('c.id', 'desc')
				    ->setMaxResults($limit)
				    ->getQuery()
				    ->getResult();
	}
}
