<?php

namespace Movies\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getAllUsersQuery()
	{
		return $this->_em
					->createQueryBuilder('u')
					->select('u')
					->from('MoviesAdminBundle:User', 'u')
					->join('u.roles', 'r')
					->orderBy('u.added', 'desc')
					->getQuery();
	}
}
