security:
   encoders:
       Movies\AdminBundle\Entity\User:
           algorithm:        sha1
           encode_as_base64: false
           iterations:       1

   role_hierarchy:
       ROLE_ADMIN:       ROLE_USER
       ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

   providers:
       administrators:
           entity: { class: MoviesAdminBundle:User, property: username }

   firewalls:
       dev:
           pattern:  ^/(_(profiler|wdt)|css|images|js)/
           security: false

       special_area:
        pattern:  ^/admin
        anonymous: ~
        form_login:
            check_path: /admin/login_check
            login_path: /admin/login
        logout:
            path:   /admin/logout
            target: /admin/login

       general_area:
        pattern:  ^/fr
        anonymous: ~
        form_login:
            check_path: /fr/user/login_check
            login_path: /fr/user/login
        logout:
            path:   /fr/user/logout
            target: /fr/home

   access_control:
    - { path: ^/_internal, role: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
    - { path: ^/fr/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: /admin/.*, role: ROLE_ADMIN }